### ISSUE TITLE
make build error (1)

### ISSUE THREAD

**Issue by Artysteel** [alexbakker/EchoBot#2]
mkdir avbot
git clone https://github.com/Impyy/EchoBot avbot
cd avbot
make

mkdir -p bin
gcc -std=gnu99 -Wall -g  -o bin/echobot src/*.c -lpthread -lsodium -ltoxcore -ltoxav
src/echobot.c: In function ‘run_tox’:
src/echobot.c:88:3: error: too few arguments to function ‘tox_iterate’
   tox_iterate(tox);
   ^
In file included from src/echobot.c:8:0:
/usr/local/include/tox/tox.h:984:6: note: declared here
 void tox_iterate(Tox *tox, void *user_data);
      ^
src/echobot.c: In function ‘main’:
src/echobot.c:338:2: error: too many arguments to function ‘tox_callback_self_connection_status’
  tox_callback_self_connection_status(g_tox, self_connection_status, NULL);
  ^
In file included from src/echobot.c:8:0:
/usr/local/include/tox/tox.h:972:6: note: declared here
 void tox_callback_self_connection_status(Tox *tox, tox_self_connection_status_cb *callback);
      ^
src/echobot.c:339:2: error: too many arguments to function ‘tox_callback_friend_request’
  tox_callback_friend_request(g_tox, friend_request, NULL);
  ^
In file included from src/echobot.c:8:0:
/usr/local/include/tox/tox.h:1742:6: note: declared here
 void tox_callback_friend_request(Tox *tox, tox_friend_request_cb *callback);
      ^
src/echobot.c:340:2: error: too many arguments to function ‘tox_callback_friend_message’
  tox_callback_friend_message(g_tox, friend_message, NULL);
  ^
In file included from src/echobot.c:8:0:
/usr/local/include/tox/tox.h:1758:6: note: declared here
 void tox_callback_friend_message(Tox *tox, tox_friend_message_cb *callback);
      ^
src/echobot.c:341:2: error: too many arguments to function ‘tox_callback_file_recv’
  tox_callback_file_recv(g_tox, file_recv, NULL);
  ^
In file included from src/echobot.c:8:0:
/usr/local/include/tox/tox.h:2268:6: note: declared here
 void tox_callback_file_recv(Tox *tox, tox_file_recv_cb *callback);
      ^
makefile:8: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by alexbakker** [comment]
EchoBot is not compatible with TokTok's fork of toxcore.

**Comment by zoff99** [comment]
@Artysteel if you just want a crappy sample application that compiles with the new c-toxcore and echos stuff try this:

https://github.com/zoff99/ToxDoorspy/tree/master/toxdoorspy

**Comment by Artysteel** [comment]
Well I have both ctoxcore and toxcore. Modified this echobot and made it to work. Currently I am trying to understand how to call from one device(linux) to another (not like here, that I can hear myself - still usefull for testing)

I am building this stuff on raspberry pi 2.

@zoff99 Thanks for that, will look into this.

**Comment by zoff99** [comment]
i do cross compiling for the raspberry PI:

https://circleci.com/gh/zoff99/ToxDoorspy/58#artifacts
