### ISSUE TITLE
bot offline

### ISSUE THREAD

**Issue by fftmp** [alexbakker/EchoBot#3]
Bot with ID from README.md is constantly offline. If you do not plan to turn it on, may be better to remove ID from .md file?

**Comment by alexbakker** [comment]
It's meant to be online 24/7, but I can't constantly monitor it, so people have to notify me when it goes offline. I restarted it, it should be back up now.

**Comment by therealmaxmoon** [comment]
The bot is offline again.

@alexbakker What is the best way to notify you?

**Comment by alexbakker** [comment]
I've restarted it. It should be back online now. You can send me a message on freenode (username is Impyy) or you can send me an email (see Github profile)
