### ISSUE TITLE
Toxcore version (question)

### ISSUE THREAD

**Issue by hkarel** [alexbakker/EchoBot#4]
Hi,
Tell me what version of toxcore is currently using EchoBot? More than 0.2.0 or less? 
I'm asking about EchoBot with toxid:  76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6
Thanks.

**Comment by alexbakker** [comment]
It's running c-toxcore version 0.1.11.
