### ISSUE TITLE
EchoBot often generates tox_friend_connection_status event

### ISSUE THREAD

**Issue by hkarel** [alexbakker/EchoBot#5]
For testing my client, I use your EchoBot ( 76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39218F515C39A6)
I began to notice that EchoBot very often generates the event tox_friend_connection_status. Other friends generate this event much less often. 
Below I quote log of my tox-client. 
[toxphone.log](https://github.com/alexbakker/EchoBot/files/1887453/toxphone.log)

**Comment by alexbakker** [comment]
I've seen this kind of behavior from other clients with large friend lists, like GroupBot. I think this is an issue with toxcore, not with EchoBot.
