### ISSUE TITLE
Transition to the new version of the toxcore due to the vulnerability found

### ISSUE THREAD

**Issue by hkarel** [alexbakker/EchoBot#6]
Is there any plan for the transition to a new version of the toxcore (0.2.2) in connection with the vulnerability found ([Onion vulnerability](https://github.com/TokTok/c-toxcore/issues/873))?

**Comment by alexbakker** [comment]
EchoBot is already running the latest version of c-toxcore. Sending it the '!info' command now also shows the exact version that it's using.

**Comment by hkarel** [comment]
Thanks!
