### ISSUE TITLE
I finally got it to compile but I get an error 2

### ISSUE THREAD

**Issue by doggodanubus** [alexbakker/EchoBot#8]
Could not bootstrap, error: 2

I compiled c-toxcore and got that installed in opt. I modified the makefile CFLAGS to have -L/opt/lib then I ram make and got the binary. I ran the binary in the bin folder to see if it worked and I got this error. I've not installed it in opt nor tried the systemd setup.

**Comment by alexbakker** [comment]
It's possible that the baked in bootstrap node is no longer online. Could you try replacing it with one from https://nodes.tox.chat and see if that helps?

**Comment by doggodanubus** [comment]
*doh* I had seen that earlier and not thought of it for this program. It's working now. The Echobot I had a key for which was from here quit working but the key here brought it back. The link the key points to https://toxme.io/u/echobot is 404. 

I am going to run this and run a bootstrap node. Thanks.
